- name: Deploy PrestaShop Apache site configuration
  template:
    src: prestashop.conf.j2
    dest: /etc/apache2/sites-available/prestashop.conf
    mode: '0644'
  notify: Reload apache2 service

- name: Enable PrestaShop site
  command: a2ensite prestashop
  args:
    creates: /etc/apache2/sites-enabled/prestashop.conf
  notify: Reload apache2 service

- name: Disable default Apache site
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Reload apache2 service

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  notify: Reload apache2 service

- name: Ensure Apache service is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
