skip_list:
  - name
  - fqcn
  - var-naming
  - risky-file-permissions
  - package-latest
  - no-handler
  - no-changed-when
  - command-instead-of-shell
  - name-casing
  - yaml-truthy
  - yaml-new-line-at-end-of-file
  - yaml-comments
  - yaml-line-length