- apt:
    name:
      - keepalived
    state: present
    update_cache: yes

- template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: restart keepalived

