- name: Install Keepalived
  apt:
    name:
      - keepalived
    state: present
    update_cache: yes

- name: Deploy keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived
