- template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
    mode: '0644'
  notify: restart apache2

- command: a2ensite wordpress
  args:
    creates: /etc/apache2/sites-enabled/wordpress.conf
  notify: restart apache2


- command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2


- command: a2enmod rewrite
  notify: restart apache2


- service:
    name: apache2
    state: started
    enabled: true


