- name: Install required packages for WordPress
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-curl
      - php-xml
      - php-gd
      - mariadb-client
      - unzip
      - curl
    update_cache: yes

- name: Ensure WordPress install directory exists
  file:
    path: "{{ wordpress_install_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

- name: Download WordPress core
  shell: wp core download --allow-root --path={{ wordpress_install_path }}
  args:
    creates: "{{ wordpress_install_path }}/wp-config-sample.php"

- name: Create WordPress config file
  shell: >
    wp config create
    --dbname={{ wordpress_db_name }}
    --dbuser={{ wordpress_db_user }}
    --dbpass={{ hostvars['localhost'].wordpress_db_password }}
    --dbhost=192.168.27.158
    --path={{ wordpress_install_path }}
    --allow-root
  args:
    creates: "{{ wordpress_install_path }}/wp-config.php"

- name: Install WordPress core
  shell: |
    wp core install \
      --url="{{ wordpress_site_url }}" \
      --title="My WordPress Site" \
      --admin_user=admin \
      --admin_password=admin123 \
      --admin_email=admin@example.com \
      --path={{ wordpress_install_path }} \
      --allow-root
  args:
    creates: "{{ wordpress_install_path }}/.installed"
  become: true

- name: Set ownership for WordPress directory
  file:
    path: "{{ wordpress_install_path }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted
