- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present

- name: Ensure MariaDB service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install python3-PyMySQL on Debian
  package:
    name: python3-pymysql
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure MariaDB to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MariaDB

- name: Run mysql_secure_installation script
  script: files/mysql_secure_installation.sh
  become: yes

- name: Create WordPress database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create WordPress user
  mysql_user:
    name: wp_user
    password: "{{ hostvars['localhost'].wordpress_db_password }}"
    host: "192.168.27.156"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create PrestaShop user
  mysql_user:
    name: ps_user
    password: ps_password
    host: "192.168.27.157"
    priv: "prestashop.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow MariaDB port through UFW
  ufw:
    rule: allow
    port: 3306
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
