- apt:
    name: mariadb-server
    state: present

- service:
    name: mariadb
    state: started
    enabled: yes

- name: Install python3-PyMySQL
  package:
    name: python3-pymysql
    state: present
  when: ansible_os_family == 'Debian'

- lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mariadb

- script: files/mysql_secure_installation.sh
  become: yes

- community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- community.mysql.mysql_user:
    name: wp_user
    password: "{{ hostvars['localhost'].wordpress_db_password }}"
    host: "192.168.27.156"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- community.mysql.mysql_user:
    name: ps_user
    password: ps_password
    host: "192.168.27.157"
    priv: "prestashop.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- apt:
    name: ufw
    state: present

- ufw:
    rule: allow
    port: 22
    proto: tcp

- ufw:
    rule: allow
    port: 3306
    proto: tcp

- ufw:
    state: enabled



