- name: Download apache_exporter
  get_url:
    url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v0.11.0/apache_exporter-0.11.0.linux-amd64.tar.gz"
    dest: /tmp/apache_exporter.tar.gz

- name: Extract apache_exporter archive
  unarchive:
    src: /tmp/apache_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create systemd unit file for apache_exporter
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
  notify: Restart Apache Exporter

- name: Start and enable apache_exporter service
  systemd:
    name: apache_exporter
    enabled: yes
    state: started
