- name: Download keepalived_exporter archive
  get_url:
    url: "https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.0/keepalived-exporter-1.3.0.linux-amd64.tar.gz"
    dest: /tmp/keepalived_exporter.tar.gz

- name: Create temp directory for keepalived_exporter extraction
  file:
    path: /usr/local/bin/keepalived_exporter_tmp/
    state: directory
    mode: '0755'

- name: Extract keepalived_exporter archive
  unarchive:
    src: /tmp/keepalived_exporter.tar.gz
    dest: /usr/local/bin/keepalived_exporter_tmp/
    remote_src: yes
#    extra_opts: [--strip-components=1]

- name: Move binary to /usr/local/bin
  copy:
    src: /usr/local/bin/keepalived_exporter_tmp/keepalived-exporter
    dest: /usr/local/bin/keepalived-exporter
    remote_src: yes
    mode: '0755'

- name: Remove temporary extraction directory
  file:
    path: /usr/local/bin/keepalived_exporter_tmp
    state: absent

- name: Create systemd unit file for keepalived_exporter
  template:
    src: keepalived_exporter.service.j2
    dest: /etc/systemd/system/keepalived_exporter.service
  notify: Restart Keepalived Exporter

- name: Start and enable keepalived_exporter service
  systemd:
    name: keepalived_exporter
    enabled: yes
    state: started
