- name: Create Prometheus directory
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: compose.yml
    dest: "{{ prometheus_dir }}/compose.yml"

- name: Generate prometheus.yml from template
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus.yml"
  notify: restart prometheus

- name: Copy alert.rules.yml file
  copy:
    src: alert.rules.yml
    dest: "{{ prometheus_dir }}/alert.rules.yml"

- name: Copy Alertmanager directory
  copy:
    src: alertmanager/
    dest: "{{ prometheus_dir }}/alertmanager/"
    mode: '0755'
    owner: root
    group: root

- name: Create Grafana directory
  file:
    path: "{{ prometheus_dir }}/grafana"
    state: directory
    owner: 472
    group: 472
    mode: '0755'

- name: Start Prometheus stack with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    files:
      - compose.yml
    state: restarted
