- name: Download mysqld_exporter
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.0/mysqld_exporter-0.15.0.linux-amd64.tar.gz"
    dest: /tmp/mysql_exporter.tar.gz

- name: Extract mysqld_exporter
  unarchive:
    src: /tmp/mysql_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create mysql_exporter systemd unit
  template:
    src: mysql_exporter.service.j2
    dest: /etc/systemd/system/mysql_exporter.service
  notify: restart mysql_exporter

- name: Start mysql_exporter
  systemd:
    name: mysql_exporter
    enabled: true
    state: started
