- name: Download mysqld_exporter archive
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.0/mysqld_exporter-0.15.0.linux-amd64.tar.gz"
    dest: /tmp/mysql_exporter.tar.gz

- name: Extract mysqld_exporter archive
  unarchive:
    src: /tmp/mysql_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create systemd unit file for mysql_exporter
  template:
    src: mysql_exporter.service.j2
    dest: /etc/systemd/system/mysql_exporter.service
  notify: Restart MySQL Exporter

- name: Start and enable mysql_exporter service
  systemd:
    name: mysql_exporter
    enabled: yes
    state: started
