keepalived_interface: ens33
keepalived_priority: 100

wordpress_ip: "{{ hostvars[groups['wordpress'][0]].ansible_host }}"
prestashop_ip: "{{ hostvars[groups['prestashop'][0]].ansible_host }}"

nginx_backend_servers: >-
  {{ groups['wordpress'] + groups['prestashop'] |
     map('extract', hostvars, 'ansible_host') |
     list }}