- name: restart prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    state: restarted

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart apache_exporter
  systemd:
    name: apache_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart nginx_exporter
  systemd:
    name: nginx_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart mysql_exporter
  systemd:
    name: mysql_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart keepalived_exporter
  systemd:
    name: keepalived_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded