- name: Restart Prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    state: restarted

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Apache Exporter
  systemd:
    name: apache_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Nginx Exporter
  systemd:
    name: nginx_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart MySQL Exporter
  systemd:
    name: mysql_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Keepalived Exporter
  systemd:
    name: keepalived_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
