name: "Déploiement avec Ansible"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Déploiement Service"
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Création de l'environnement virtuel + Ansible
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Installer sshpass
        run: |
          sudo apt-get install -y sshpass

      - name: Exécution du playbook Ansible
        run: |
          source .venv/bin/activate
          ansible-playbook -i inventory.yml deploy.yml

