name: "Deployment with Ansible"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Service Deployment"
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create virtual environment and install Ansible
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Ansible Linter
        run: |
          source .venv/bin/activate
          ansible-lint -i inventory.yml deploy.yml

      - name: Run Ansible playbook
        run: |
          source .venv/bin/activate
          ansible-playbook -i inventory.yml deploy.yml
